Step3
Dinaelin-Yip/mercari-build-training pull request #2
Opened 2024-02-19 10:00 UTC by Dinaelin-Yip

## What

"python/Step3.md" illustrates the answers of point questions.
"python/items.json" and "python/main.py" are basic api files to meet requirements.

## CHECKS :warning:

Please make sure you are aware of the following.

- [ ] **The changes in this PR doesn't have private information

2024-02-19 15:17 UTC, zeph-09 requested changes

2024-02-19 15:17 UTC, zeph-09 commented on python/main.py
> +    save_items_json(items, cur_max_id)
Same, check if the save_items_json is executed without any errors. Also, send responses along with appropriate status codes.

2024-02-19 15:17 UTC, zeph-09 commented on python/main.py
> +    items_path = pathlib.Path(__file__).parent.resolve() / "items.json"
Add a try except block to catch unhandled errors.

2024-02-19 15:17 UTC, zeph-09 commented on python/main.py
> +    else:
Would be better if we send a appropriate message like, unable to fetch items from JSON. 
Since sending an empty array means, there is no data which is a contradiction.

2024-02-19 15:17 UTC, zeph-09 commented on python/main.py
> +    print(items, cur_max_id)
Dont use print statements, instead use Logger.

2024-02-20 01:20 UTC, Dinaelin-Yip commented on python/main.py
> +    save_items_json(items, cur_max_id)
In the function save_items_json(), if the json file does not exist,
raise HTTPException(status_code=404, detail="Unable to write the item file.")
in row 48

2024-02-20 01:23 UTC, Dinaelin-Yip commented on python/main.py
> +    else:
If it's unable to fetch items from JSON,
raise HTTPException(status_code=404, detail="Unable to fetch items from json.")
in row 37.

2024-02-20 01:27 UTC, Dinaelin-Yip commented on python/main.py
> +    save_items_json(items, cur_max_id)
In row 48,
raise HTTPException(status_code=404, detail="Unable to write the item file.")

2024-02-20 01:28 UTC, Dinaelin-Yip commented on python/main.py
> +def get_item(item_id):
In row 70,
raise HTTPException(status_code=404, detail="This id does not exist!")

2024-02-20 01:28 UTC, Dinaelin-Yip commented on python/main.py
> +    else:
In row 37,
raise HTTPException(status_code=404, detail="Unable to fetch items from json.")

2024-02-20 01:29 UTC, Dinaelin-Yip commented on python/main.py
> +    print(items, cur_max_id)
I used print since I wanted to check if the value of items were correct. I have deleted it.

2024-02-20 10:09 UTC, zeph-09 commented
Good Work, Approved, but add some info and error logs as well. 👍

2024-02-20 13:03 UTC, merged

2024-02-20 23:27 UTC, codesuki commented on python/main.py
> +os.chdir('/Users/xiaotongye/Programs/mercari-build-training/python')
You probably don't want to depend on the location of the program like this, because if you copy it to somewhere else it might not work anymore.

2024-02-20 23:32 UTC, codesuki commented on python/main.py
> +    save_items_json(items, cur_max_id)
It would be great if the code on line 48 would not know that it's used in a HTTP service. I would propose to have `save_items_json` return a generic error and your HTTP handler `add_item` to check for this and return the appropriate HTTP status code, etc. This way you have some separation of concerns.